-- Performance Alerts for Scout plan
-- Created 2026-05-30 · Sprint 3
--
-- Lets Scout users subscribe to performance alerts on specific players.
-- When the player scores / assists / hat-tricks above their threshold, we
-- email them via Resend (cron: app/api/cron/performance-alerts/route.ts,
-- ideally scheduled */30 * * * * on match days, see vercel.json).
--
-- Apply via Supabase MCP (project dsomnamtjcenhkyifbon) OR `supabase db push`.

create table if not exists public.performance_alerts (
  id           bigint generated by default as identity primary key,
  clerk_id     text   not null,
  email        text   not null,
  player_slug  text   not null,
  player_name  text   not null,
  alert_type   text   not null check (alert_type in ('goal','brace','hat_trick','assist','rating_85')),
  enabled      boolean not null default true,
  created_at   timestamptz not null default now(),
  last_fired_at timestamptz
);

create index if not exists performance_alerts_clerk_idx
  on public.performance_alerts (clerk_id) where enabled;
create unique index if not exists performance_alerts_uniq_idx
  on public.performance_alerts (clerk_id, player_slug, alert_type);

-- Track which match-events have already triggered an alert so reruns don't
-- double-send. Keys on (player_slug, match_id, alert_type).
create table if not exists public.performance_alert_events (
  id           bigint generated by default as identity primary key,
  player_slug  text   not null,
  match_id     text   not null,
  alert_type   text   not null,
  fired_at     timestamptz not null default now(),
  details      jsonb
);

create unique index if not exists performance_alert_events_uniq
  on public.performance_alert_events (player_slug, match_id, alert_type);

-- RLS: users can only see and manage their own subscriptions.
alter table public.performance_alerts enable row level security;

drop policy if exists "self_select" on public.performance_alerts;
create policy "self_select" on public.performance_alerts
  for select using (clerk_id = current_setting('request.jwt.claims', true)::jsonb->>'sub');

drop policy if exists "self_insert" on public.performance_alerts;
create policy "self_insert" on public.performance_alerts
  for insert with check (clerk_id = current_setting('request.jwt.claims', true)::jsonb->>'sub');

drop policy if exists "self_update" on public.performance_alerts;
create policy "self_update" on public.performance_alerts
  for update using (clerk_id = current_setting('request.jwt.claims', true)::jsonb->>'sub');

drop policy if exists "self_delete" on public.performance_alerts;
create policy "self_delete" on public.performance_alerts
  for delete using (clerk_id = current_setting('request.jwt.claims', true)::jsonb->>'sub');

-- Events table is server-only (service role writes/reads). No public access.
alter table public.performance_alert_events enable row level security;
