// Nationality → flag emoji. Resilient to the different forms our sources use:
// API-Football returns country names ("Spain", "England"), while curated data
// sometimes uses adjectives ("Spanish") or Spanish adjectives ("Argentino").
// Keyed by normalized lowercase alias.

const FLAGS: Record<string, string> = {}
const norm = (s: string) => s.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
function add(emoji: string, ...aliases: string[]) {
  for (const a of aliases) { FLAGS[a.toLowerCase()] = emoji; FLAGS[norm(a)] = emoji }
}

add('🇪🇸', 'Spain', 'Spanish', 'España', 'Español', 'Espanol', 'Española')
add('🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'England', 'English', 'Inglaterra', 'Inglés', 'Ingles')
add('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Scotland', 'Scottish', 'Escocia')
add('🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'Wales', 'Welsh', 'Gales')
add('🇬🇧', 'Great Britain', 'Northern Ireland', 'Irlanda del Norte')
add('🇮🇪', 'Ireland', 'Irish', 'Republic of Ireland', 'Irlanda')
add('🇫🇷', 'France', 'French', 'Francia', 'Francés', 'Frances')
add('🇩🇪', 'Germany', 'German', 'Alemania', 'Alemán', 'Aleman')
add('🇮🇹', 'Italy', 'Italian', 'Italia', 'Italiano')
add('🇵🇹', 'Portugal', 'Portuguese', 'Portugués', 'Portugues')
add('🇳🇱', 'Netherlands', 'Dutch', 'Holanda', 'Países Bajos', 'Holandés')
add('🇧🇪', 'Belgium', 'Belgian', 'Bélgica', 'Belga')
add('🇧🇷', 'Brazil', 'Brazilian', 'Brasil', 'Brasileño', 'Brasileiro')
add('🇦🇷', 'Argentina', 'Argentine', 'Argentinian', 'Argentino')
add('🇺🇾', 'Uruguay', 'Uruguayan', 'Uruguayo')
add('🇨🇴', 'Colombia', 'Colombian', 'Colombiano')
add('🇨🇱', 'Chile', 'Chilean', 'Chileno')
add('🇵🇪', 'Peru', 'Peruvian', 'Perú', 'Peruano')
add('🇪🇨', 'Ecuador', 'Ecuadorian', 'Ecuatoriano')
add('🇵🇾', 'Paraguay', 'Paraguayan', 'Paraguayo')
add('🇻🇪', 'Venezuela', 'Venezuelan', 'Venezolano')
add('🇧🇴', 'Bolivia', 'Bolivian', 'Boliviano')
add('🇲🇽', 'Mexico', 'Mexican', 'México', 'Mexicano')
add('🇺🇸', 'USA', 'United States', 'American', 'Estados Unidos', 'Estadounidense')
add('🇨🇦', 'Canada', 'Canadian', 'Canadá')
add('🇨🇷', 'Costa Rica', 'Costa Rican', 'Costarricense')
add('🇭🇳', 'Honduras', 'Honduran', 'Hondureño')
add('🇵🇦', 'Panama', 'Panamanian', 'Panamá', 'Panameño')
add('🇯🇲', 'Jamaica', 'Jamaican')
add('🇳🇴', 'Norway', 'Norwegian', 'Noruega', 'Noruego')
add('🇸🇪', 'Sweden', 'Swedish', 'Suecia', 'Sueco')
add('🇩🇰', 'Denmark', 'Danish', 'Dinamarca', 'Danés', 'Danes')
add('🇫🇮', 'Finland', 'Finnish', 'Finlandia')
add('🇮🇸', 'Iceland', 'Icelandic', 'Islandia')
add('🇨🇭', 'Switzerland', 'Swiss', 'Suiza', 'Suizo')
add('🇦🇹', 'Austria', 'Austrian', 'Austria', 'Austríaco')
add('🇵🇱', 'Poland', 'Polish', 'Polonia', 'Polaco')
add('🇨🇿', 'Czech Republic', 'Czech-Republic', 'Czech', 'Chequia', 'Checo')
add('🇸🇰', 'Slovakia', 'Slovak', 'Eslovaquia', 'Eslovaco')
add('🇭🇺', 'Hungary', 'Hungarian', 'Hungría', 'Húngaro')
add('🇷🇴', 'Romania', 'Romanian', 'Rumanía', 'Rumano')
add('🇷🇸', 'Serbia', 'Serbian', 'Serbio')
add('🇭🇷', 'Croatia', 'Croatian', 'Croacia', 'Croata')
add('🇸🇮', 'Slovenia', 'Slovenian', 'Slovene', 'Eslovenia', 'Esloveno')
add('🇧🇦', 'Bosnia and Herzegovina', 'Bosnia', 'Bosnian', 'Bosnia-Herzegovina')
add('🇲🇪', 'Montenegro', 'Montenegrin')
add('🇲🇰', 'North Macedonia', 'Macedonia', 'Macedonian')
add('🇦🇱', 'Albania', 'Albanian', 'Albanés', 'Albanes')
add('🇽🇰', 'Kosovo', 'Kosovar')
add('🇧🇬', 'Bulgaria', 'Bulgarian', 'Búlgaro')
add('🇬🇷', 'Greece', 'Greek', 'Grecia', 'Griego')
add('🇹🇷', 'Turkey', 'Türkiye', 'Turkish', 'Turquía', 'Turco')
add('🇺🇦', 'Ukraine', 'Ukrainian', 'Ucrania', 'Ucraniano')
add('🇷🇺', 'Russia', 'Russian', 'Rusia', 'Ruso')
add('🇧🇾', 'Belarus', 'Belarusian')
add('🇬🇪', 'Georgia', 'Georgian', 'Georgiano')
add('🇦🇲', 'Armenia', 'Armenian')
add('🇮🇱', 'Israel', 'Israeli', 'Israelí')
add('🇲🇦', 'Morocco', 'Moroccan', 'Marruecos', 'Marroquí', 'Marroqui')
add('🇩🇿', 'Algeria', 'Algerian', 'Argelia', 'Argelino')
add('🇹🇳', 'Tunisia', 'Tunisian', 'Túnez', 'Tunecino')
add('🇪🇬', 'Egypt', 'Egyptian', 'Egipto', 'Egipcio')
add('🇸🇳', 'Senegal', 'Senegalese', 'Senegalés', 'Senegales')
add('🇨🇮', 'Ivory Coast', 'Côte d\'Ivoire', 'Ivorian', 'Costa de Marfil', 'Marfileño')
add('🇬🇭', 'Ghana', 'Ghanaian', 'Ghanés')
add('🇳🇬', 'Nigeria', 'Nigerian', 'Nigeriano')
add('🇨🇲', 'Cameroon', 'Cameroonian', 'Camerún', 'Camerunés')
add('🇲🇱', 'Mali', 'Malian', 'Malí', 'Maliense')
add('🇬🇳', 'Guinea', 'Guinean', 'Guineano')
add('🇧🇫', 'Burkina Faso', 'Burkinabe')
add('🇨🇩', 'DR Congo', 'Congo DR', 'Congo', 'Congolese')
add('🇨🇬', 'Congo Republic')
add('🇬🇦', 'Gabon', 'Gabonese')
add('🇿🇦', 'South Africa', 'South African', 'Sudáfrica')
add('🇦🇴', 'Angola', 'Angolan', 'Angoleño')
add('🇨🇻', 'Cape Verde', 'Cape Verdean')
add('🇯🇵', 'Japan', 'Japanese', 'Japón', 'Japonés')
add('🇰🇷', 'South Korea', 'Korea Republic', 'Korean', 'Corea del Sur', 'Coreano')
add('🇦🇺', 'Australia', 'Australian', 'Australiano')
add('🇳🇿', 'New Zealand', 'New Zealander')
add('🇨🇳', 'China', 'Chinese', 'Chino')
add('🇮🇷', 'Iran', 'Iranian', 'Irán', 'Iraní')
add('🇸🇦', 'Saudi Arabia', 'Saudi', 'Arabia Saudí')
add('🇶🇦', 'Qatar', 'Qatari')
add('🇮🇶', 'Iraq', 'Iraqi')
add('🇺🇿', 'Uzbekistan', 'Uzbek')
add('🇮🇳', 'India', 'Indian')

/** Flag emoji for a nationality string in any of the forms our sources use. */
export function flagFor(nationality?: string | null): string | undefined {
  if (!nationality) return undefined
  return FLAGS[nationality.toLowerCase()] ?? FLAGS[norm(nationality)]
}
