// AUTO-GENERATED by scripts/enrich-news-photos.mjs — do not edit by hand.
// normalized news-headline player name → API-Football player id. These are names
// that appear in football news headlines but are NOT in our SEARCH_INDEX (players
// in leagues we don't ingest — Saudi, MLS, etc.) or in a name form our matcher
// missed, so they previously fell back to a club crest / placeholder.
//
// Each id's photo was CONFIRMED REAL (not the ~5192-byte api-sports silhouette)
// at enrichment time, with precision-first name disambiguation against
// /players/profiles (exact full-name match wins; ambiguous → never cached). So
// lib/player-photo.ts treats these ids as photo-trusted and emits the headshot
// directly (bypassing the verifiedPhoto gate), same as the curated mononyms.
//
// Refresh: node scripts/enrich-news-photos.mjs   (wired to a weekly cron).
// Generated 2026-06-25 · 37 names.
export const NEWS_NAME_PHOTOS: Record<string, number> = {"achraf hakimi":9,"adolfo munoz":16477,"aitana bonmati":74276,"alex scott":304853,"alexia putellas":74234,"andre onana":526,"bamba dieng":284072,"brian cipenga":279482,"cristiano ronaldo":874,"de zerbi":393873,"diego conde":122956,"enner valencia":35533,"enzo maresca":91390,"facundo bernal":316519,"gilberto silva":41704,"ian wright":182430,"inaki williams":47294,"jack wilshere":18829,"javier aguirre":102132,"joao rego":345427,"john terry":82009,"juanjo nieto":105034,"jude bellingham":129718,"kazuyoshi miura":33837,"lionel messi":154,"mary earps":68823,"mauricio cuevas":71219,"michael owen":114815,"nestory irankunda":338014,"nico melamed":128581,"nico schlotterbeck":26243,"piero hincapie":127817,"ter stegen":127,"thapelo maseko":354831,"victor fernandez":123054,"william saliba":22090,"zaid romero":180927}
