// AUTO-GENERATED by scripts/gen-players.mjs — do not edit by hand.
// Source: API-Football top scorers + top assists, season 2025 (→ '2526').
// Generated: 2026-06-01T10:34:02.716Z
// Players already curated in data/players.ts (RAW) are intentionally excluded.
import type { PlayerData } from '@/types'

export const GENERATED_PLAYERS: PlayerData[] = [] as PlayerData[]
