/**
 * verify-photos.mjs
 *
 * Builds data/photo-verified.ts — the set of API-Football player ids that serve
 * a REAL headshot (not the generic gray silhouette).
 *
 * ROOT PROBLEM: every player id maps to a predictable photo URL
 * (media.api-sports.io/football/players/<id>.png), but ids WITHOUT a real photo
 * quietly serve a generic silhouette as HTTP 200 — a ~5192-byte PNG with md5
 * 430d67fd79ad0a355b212d5780886e34. From the URL alone we cannot tell a real
 * photo from a silhouette, so a news card can show a silhouette by mistake.
 *
 * This is a BUILD-TIME, one-off enrichment (NOT a per-request fetch): it fetches
 * each CANDIDATE id once, hashes the bytes, and records the ids whose photo is
 * real. The app then emits a news headshot ONLY for a verified id; otherwise it
 * falls back to the club crest, then a branded placeholder. Never a silhouette.
 *
 * Candidate scope (cheap): the curated stars (data/curated-ids.ts). These are
 * the marquee names news headlines are actually about and the only ids the news
 * resolver is allowed to surface as a confident headshot. Pass `--all` to also
 * verify every name/full-name phrase id from the search index (large, slow —
 * only if you intend to widen the confident-headshot set).
 *
 * Run:
 *   node scripts/verify-photos.mjs            # verify curated ids (default)
 *   node scripts/verify-photos.mjs --dry      # report only, don't write
 *   node scripts/verify-photos.mjs --all      # also verify phrase ids (slow)
 */
import { readFileSync, writeFileSync } from 'fs'
import { createHash } from 'crypto'
import https from 'https'
import { setTimeout as sleep } from 'timers/promises'

const SILHOUETTE_MD5 = '430d67fd79ad0a355b212d5780886e34'
const SILHOUETTE_SIZE = 5192
const DRY = process.argv.includes('--dry')
const ALL = process.argv.includes('--all')

function getBuf(url) {
  return new Promise((resolve) => {
    const chunks = []
    const req = https.get(url, (r) => {
      r.on('data', (c) => chunks.push(c))
      r.on('end', () => resolve({ status: r.statusCode, buf: Buffer.concat(chunks) }))
    })
    req.on('error', () => resolve({ status: 0, buf: Buffer.alloc(0) }))
    req.setTimeout(10000, () => { req.destroy(); resolve({ status: 0, buf: Buffer.alloc(0) }) })
  })
}

const isReal = (r) =>
  r.status === 200 &&
  r.buf.length !== SILHOUETTE_SIZE &&
  createHash('md5').update(r.buf).digest('hex') !== SILHOUETTE_MD5

// ── Candidate ids ───────────────────────────────────────────────────────────
function loadCuratedIds() {
  const src = readFileSync('data/curated-ids.ts', 'utf8')
  const map = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1))
  return new Set(Object.values(map))
}

function loadPhraseIds() {
  // name / fullName phrases (>= 2 words) → id; same indexing the news resolver
  // uses (lib/player-photo.ts pass 1). Ambiguous phrases excluded.
  const src = readFileSync('data/search-index.ts', 'utf8')
  const m = src.match(/JSON\.parse\((\"[\s\S]*\")\)/)
  const arr = JSON.parse(JSON.parse(m[1]))
  const norm = (s) => (s ?? '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9 ]/g, '').trim()
  const phrase = new Map(); const ambig = new Set()
  const add = (ph, id) => { if (!ph || ph.split(' ').length < 2) return; const c = phrase.get(ph); if (c === undefined) phrase.set(ph, id); else if (c !== id) ambig.add(ph) }
  for (const p of arr) { if (!p.id) continue; add(norm(p.name), p.id); if (p.fullName) add(norm(p.fullName), p.id) }
  const ids = new Set()
  for (const [ph, id] of phrase) if (!ambig.has(ph)) ids.add(id)
  return ids
}

const candidates = new Set(loadCuratedIds())
if (ALL) for (const id of loadPhraseIds()) candidates.add(id)
const ids = [...candidates].filter(Boolean).sort((a, b) => a - b)
console.error(`Verifying ${ids.length} candidate ids${ALL ? ' (curated + phrase)' : ' (curated)'}…`)

const verified = []; const blocked = []; const errored = []
let n = 0
for (const id of ids) {
  const r = await getBuf(`https://media.api-sports.io/football/players/${id}.png`)
  if (r.status === 0) errored.push(id)
  else if (isReal(r)) verified.push(id)
  else blocked.push(id)
  if (++n % 50 === 0) { console.error(`  …${n}/${ids.length}`); await sleep(200) }
}

verified.sort((a, b) => a - b)
console.error(`Real photo: ${verified.length} · silhouette/blocked: ${blocked.length} · fetch-error: ${errored.length}`)
if (blocked.length) console.error('BLOCKED (silhouette):', blocked.join(', '))
if (errored.length) console.error('ERRORED (left out — not verified):', errored.join(', '))

if (DRY) { console.error('--dry: not writing.'); process.exit(0) }

const out = `// AUTO-GENERATED by scripts/verify-photos.mjs — do not edit by hand.
// API-Football player ids CONFIRMED to serve a REAL headshot (not the generic
// gray silhouette media.api-sports.io returns — HTTP 200, ~${SILHOUETTE_SIZE}-byte PNG,
// md5 ${SILHOUETTE_MD5} — for ids without a photo).
//
// WHY: every player id resolves to a predictable /players/<id>.png URL, but
// photo-less ids quietly serve that silhouette as a 200. We can NOT tell them
// apart from the URL alone, and we must never show a silhouette on a news card.
// So a news headshot is emitted ONLY for an id in this verified set; otherwise
// the visual falls back to the club crest, then a branded placeholder.
//
// Generated ${new Date().toISOString().slice(0, 10)} from ${ALL ? 'curated + search-index phrase ids' : 'the curated stars (data/curated-ids.ts)'}.
// Re-run scripts/verify-photos.mjs after editing curated-ids.ts (or with --all
// to widen coverage) to refresh this set.
export const PHOTO_VERIFIED: ReadonlySet<number> = new Set([
${verified.map((id) => '  ' + id).join(',\n')},
])
`
writeFileSync('data/photo-verified.ts', out)
console.error(`Wrote data/photo-verified.ts with ${verified.length} verified ids.`)
